# Generated by Django 5.1.4 on 2024-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_alter_filepermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='encrypted_file',
            field=models.FileField(upload_to='encrypted_blobs/'),
        ),
    ]
