# Generated by Django 5.1.4 on 2024-12-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_alter_filestorage_encrypted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='global_permission_type',
            field=models.CharField(choices=[('read', 'Read-Only'), ('download', 'Download'), ('all', 'All')], default='all', max_length=25),
        ),
    ]
